import {ApolloClient, gql, InMemoryCache} from '@apollo/client'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Deck from '../components/deck/index'

const client = new ApolloClient({
  uri: 'http://localhost:4000',
  cache: new InMemoryCache()
})

const tableQry = gql`
  query {
    table {
      number 
      symbol
    }
  }
`

const handQry = gql`
  query GetCards($cards: Int) {
    getCards(cards: $cards) {
      number
      symbol
    }
  }
`

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Cards Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <h2 className={styles.title}>{props.title}</h2>
        <Deck title="Table" cards={props.table} flipped="2"/>
        <Deck title="Hand" cards={props.hand} flipped="2"/>
      </div>

    </>
  )
}

export async function getServerSideProps(context) {
  const tableData = await client.query({
    query: tableQry
  });

  const handData = await client.query({
    query: handQry,
    variables: {cards: 2},
    fetchPolicy: 'no-cache'});  
  return {
    props: {
      title: 'Cards Next.js',
      table: tableData.data.table,
      hand: handData.data.getCards
    },
  }
}
